server:
  port: 8888

spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: ${USER_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/users/**, /cards/**
              metadata:
                response-timeout: 30000

            - id: auth-service-route
              uri: ${AUTH_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/auth/**

            - id: order-service-route
              uri: ${ORDER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/orders/**, /items/**
jwt:
  secret: ${JWT_SECRET}

url:
  user-service: ${USER_SERVICE_URL:http://localhost:8080}
  auth-service: ${AUTH_SERVICE_URL:http://localhost:8082}
  order-service: ${ORDER_SERVICE_URL:http://localhost:8081}
